// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtelHxMcrwX5Y3r6KNkTrnOUOC6aylOJk',
    appId: '1:203411705611:web:00936a2e32d4e9f1c7dc0e',
    messagingSenderId: '203411705611',
    projectId: 'hourworx',
    authDomain: 'hourworx.firebaseapp.com',
    storageBucket: 'hourworx.appspot.com',
    measurementId: 'G-C0QYQ0PFMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6N0rlO4oyMTHuFNIoCHsZ_55tf-tKVoU',
    appId: '1:203411705611:android:8dcdb7118350d05dc7dc0e',
    messagingSenderId: '203411705611',
    projectId: 'hourworx',
    storageBucket: 'hourworx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZknWYudCvdNBRWdt7n8JAgY0_MdA_xRc',
    appId: '1:203411705611:ios:7bc2a887ac5f5bfac7dc0e',
    messagingSenderId: '203411705611',
    projectId: 'hourworx',
    storageBucket: 'hourworx.appspot.com',
    iosClientId: '203411705611-t92bv6ukdv2c368g6td9ti23f5c2esqu.apps.googleusercontent.com',
    iosBundleId: 'com.onest.hrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZknWYudCvdNBRWdt7n8JAgY0_MdA_xRc',
    appId: '1:203411705611:ios:72e835f891c905e0c7dc0e',
    messagingSenderId: '203411705611',
    projectId: 'hourworx',
    storageBucket: 'hourworx.appspot.com',
    iosBundleId: 'com.example.onesthrm',
  );
}
